export const GET_COMICS_REQUEST = 'GET_COMICS_REQUEST'
export const GET_COMICS_SUCCESS = 'GET_COMICS_SUCCESS'
export const GET_COMICS_FAILURE = 'GET_COMICS_FAILURE'

export const ADD_COMIC_REQUEST = 'ADD_COMIC_REQUEST'
export const ADD_COMIC_SUCCESS = 'ADD_COMIC_SUCCESS'
export const ADD_COMIC_FAILURE = 'ADD_COMIC_FAILURE'

export const ADD_FAVOURITE_COMIC = 'ADD_FAVOURITE_COMIC'

export const REMOVE_FAVOURITE_COMIC = 'REMOVE_FAVOURITE_COMIC'
